#!/bin/sh
#$Id: lacx 7 2009-02-25 15:19:11Z j-waldby $

# Start yume with latest .c file from current dir

export YTITL=$0
export YEDIT=x2
export YOPTS="-O3 -Wall -lX11 -lforms -lXpm"
export YMAKE=make
lac $*
