#!/bin/sh
#$Id: test-y-1 7 2009-02-25 15:19:11Z j-waldby $

# Not much of a yume example, just a create-some-buttons test case
[ "$YUME" ] || YUME=$(which yume)

$YUME -ex df -at 280x280+0+300 -do date "df ." ls -bu date -la 'Bye-bye' -ex -la lsa "ls -a" -bu a b  xwininfo -ex -ti "${0}a woo hoo" &

$YUME -ex df -at 280x280+0+640     date "df ." ls -bu date -la 'Bye-bye' -ex -la lsa "ls -a" -bu a b  xwininfo -ex -ti "${0}b woo hoo" &
