#!/bin/sh
#$Id: um3 7 2009-02-25 15:19:11Z j-waldby $
[ "$YUME" ] || YUME=$(which yume)

$YUME  -bu -ti $0 \
 -la Cal3         "xterm -geometry 69x9 -fn lucidasanstypewriter-bold-24 -e 'cal -3|less' &"\
 -la cdPlay       "cdplay &"\
 -la eject        "eject /dev/cdrom &" -ex &
